### ISSUE TITLE
Padding is generated with hanging nodes

### ISSUE THREAD

**Issue by Laar** [hpgem/nanomesh#178]
Generating padding can result in a mesh with hanging nodes. See the example below:
![BadPadding](https://user-images.githubusercontent.com/731831/149782889-87235c32-25b5-47cc-8969-bf58fb0c13e1.png)

**Comment by stefsmeets** [comment]
Yeah, I have also noticed this on occasion. It has to do with the way `nanomesh` is adding the padding to the mesh. Sometimes it modifies the input points at the boundary. There is no option to avoid this in `triangle`. You can play with the mesh area (`opts=aX`) to see if you can get it to go away.

#148 will change the way padding works by first defining all the padding areas and then meshing it in one go. This will make the meshing more robust and avoid this problem altogether.

**Comment by stefsmeets** [comment]
Hi @Laar, I revised the padding so that this won't happen anymore. The code is much more robust now that I could remove some complex code to keep track of the nodes. `triangle` now does all the triangulation in one go, which will result in better meshes. See here for how to use it: https://nanomesh.readthedocs.io/en/latest/examples/How%20to%20pad%20a%202D%20mesh.html

A bonus is that `triangle` now also calculates all the cell labels, which means I could remove even more code.

There may be some loose ends (😅), so if you are missing a feature from the old implementation, let me know.
